name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Build the tool
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
  
    - name: Test with pytest
      run: |
        pip install pytest pytest-mock
        pytest
